### ISSUE TITLE
Rename "Extend" to e.g. "Representation"

### ISSUE THREAD

**Issue by nikriek** [Symatem/Symatem#1]
The word _Extend_ was a bit confusing for me at first. I suggest to choose a different name, as _Extend_'s value is the bit _Representation_ or _Real_ value, right? _Representation_ might be too long, though.

**Comment by Lichtso** [comment]
I named it _Extend_ originally because many file systems call the actual data streams _Extend_s too. But the term is used too often and for different purposes, so yes, I will rename it. But it is not a _Representation_ and not the _Real_ thing, just something additional.  
So what about _RawDataStream_ or _BitSequence_?

**Comment by nikriek** [comment]
I would go for _RawData(Stream)_

**Comment by Lichtso** [comment]
And what about [Blob](https://de.wikipedia.org/wiki/Binary_Large_Object)?
The problem with _RawData_ is: There is no plural of data, so it is quiet annoying to write the docs.

**Comment by nikriek** [comment]
Even nicer :+1:
